name: Github Action 실행하기


#main브랜티에 push 이벤트가 발생했을 때 실행되는 workflow
on:
  push:
    branches:
      - main

jobs:
  My-First-CICD-job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web
        run: echo "this is the first auto cicd step 1"

  My-Second-CICD-job:
    runs-on: ubuntu-latest

    steps:
      - name: 디렉토리 확인
        run: |
          ls -al
          pwd

      - name: file 생성
        run: |
          echo "new file" > test.txt
          ls -al

  My-Third-CICD-job:
    runs-on: ubuntu-latest

    steps:
      - name: Github 변수 확인
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: secret 변수 확인
        run: |
          echo ${{secrets.MY_KEY}}
          echo ${{secrets.MY_SECRET_KEY}}